

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taskflow-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge

volumes:
  db_data:
