events {
    worker_connections 1024;
}

http {
    # Define the upstream load balancing block
    upstream taskflow_api {
        # Docker's internal DNS will automatically resolve 'app'
        # to the IP addresses of all running replicas (e.g. 3 replicas).
        server app:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://taskflow_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
