apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: InfluxDB-k6
    type: influxdb
    uid: influxdb-k6
    url: http://influxdb:8086
    access: proxy
    isDefault: false
    database: k6
    jsonData:
      httpMode: GET
